---
abstract: 'Pure perl AMQP client for RabbitMQ'
author:
  - emarcotte@athenahealth.com
build_requires:
  Test::Exception: 0.24
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-AMQP-RabbitMQ
provides:
  Net::AMQP::RabbitMQ:
    file: lib/Net/AMQP/RabbitMQ.pm
    version: 0.01
recommends:
  Socket::Linux: 0.01
requires:
  File::ShareDir: 1
  List::MoreUtils: 0.25
  Net::AMQP: 0.06
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
